[database]
database_url= "mysql://root@127.0.0.1:3306/hero-dev-api"

[redis]
redis_address= "redis://127.0.0.1:6379"

[app]
allowed_origins= "http://localhost:3000"

[auth]
secret= "herohero"
issuer= "herohero"
expiry= 2400

[log]
filter= "hero-api"
